version: '3.9'
services:
  app:
    image: my-react
    build:
      context: .
    container_name: app
    ports:
      - 80:80
      - 8000:8000
      - 8080:8080
      - 8888:8888
    env_file:
      - .env
    volumes:
      - ./app:/app
    working_dir: /app
    stdin_open: true
    tty: true
