version: '3.9'

services:
  app:
    image: my-streamlit
    build:
      context: .
    container_name: app
    volumes:
      - ./main.py:/app/main.py
      - ./pages:/app/pages
      - ./mymodule:/app/mymodule
      - ./data:/app/data
      - ./.streamlit/config.toml:/app/.streamlit/config.toml
    ports:
      - 8888:8888
    stdin_open: true
    tty: true
    command: [ "streamlit", "run", "main.py" ]
