version: '3.9'
services:
  app:
    image: myyarn
    build:
      context: .
    container_name: mynode
    ports:
      - 80:80
      - 8000:8000
      - 8080:8080
      - 8888:8888
    volumes:
      - ./:/src
    working_dir: /src
    stdin_open: true
    tty: true
