version: "3.9"

services:
  web:
    build:
      context: .
      args:
        INSTALL_OPTION: "--without dev"
    container_name: web
    ports:
      - 8000:8000
      - 8080:8080
      - 8888:8888
      - 9000:9000
