version: "3.9"
x-environment:
  &default-environment
  env_file:
    - .env

services:
  web:
    build:
      context: .
      args:
        INSTALL_OPTION: "--without dev"
    container_name: web
    ports:
      - 8000:8000
      - 8080:8080
      - 8888:8888
      - 9000:9000
    << : *default-environment
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - vol-db:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    << : *default-environment

volumes:
  vol-db:
