version: '3.9'
services:
  app:
    image: my-vue
    build:
      context: .
    container_name: vuetiful
    environment:
      - NODE_ENV=development
    ports:
      - 80:80
      - 8000:8000
      - 8080:8080
      - 8888:8888
    volumes:
      - ./app:/app
    working_dir: /app
    stdin_open: true
    tty: true
