#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER mysite WITH PASSWORD '$POSTGRES_PASSWORD';
	CREATE DATABASE mysite;
	GRANT ALL PRIVILEGES ON DATABASE mysite TO mysite;
EOSQL
