services:
  app:
    image: sample
    build:
      context: .
      target: app
    ports:
      - 8888:8000
    depends_on:
      - redis
    volumes:
      - ./app:/app

  client:
    image: client
    build:
      context: .
      target: client
    volumes:
      - ./data:/client/data

  redis:
    image: redis:6.2.18
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
